# Generated by Django 4.1.2 on 2022-12-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_pic_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('storyline', models.CharField(max_length=300)),
                ('imageUrl', models.URLField()),
                ('trailer_url', models.URLField()),
                ('actors', models.ManyToManyField(related_name='acted', to='api.cast')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='directed', to='api.cast')),
            ],
        ),
    ]
