# Generated by Django 4.1.2 on 2022-12-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_alter_movie_director_review_recommend_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='api.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='api.comment'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='acted', to='api.cast'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
