# Generated by Django 4.1.2 on 2022-12-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_movie_director_alter_movie_trailer_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='movie', to='api.tags'),
        ),
    ]
