# Generated by Django 4.1.2 on 2022-12-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_movie_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='comments', to='api.user'),
        ),
    ]
