# Generated by Django 4.1.2 on 2022-12-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_comment_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
