# Generated by Django 4.1.2 on 2022-12-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_review_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='upvoted_comments', to='api.user'),
        ),
        migrations.AddField(
            model_name='movie',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='upvoted_reviews', to='api.user'),
        ),
    ]
