# Generated by Django 4.1.2 on 2022-12-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.URLField(blank=True),
        ),
    ]
