# Generated by Django 4.1.2 on 2022-12-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_cast_profile_pic_url_alter_movie_cardimageurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
