# Generated by Django 4.1.2 on 2022-12-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_movie_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='storyline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
