# Generated by Django 4.1.2 on 2023-01-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_upvoted_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked_movies',
            field=models.ManyToManyField(related_name='bookmarked_by', to='api.movie'),
        ),
    ]
