# Generated by Django 4.1.2 on 2023-01-07 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_comment_timestamp_alter_review_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
